In [1]:
import pandas as pd


In [2]:
data=pd.read_csv("https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv")

In [4]:
data

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [9]:
import sklearn
from sklearn.model_selection import train_test_split

In [10]:
x=data['Hours']
y=data['Scores']

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression 

In [24]:
from sklearn.linear_model import LinearRegression 

In [34]:
lr=LinearRegression()
import numpy as np
X_tr=np.array(x_train).reshape(-1,1)
lr.fit(X_tr,y_train)

LinearRegression()

In [35]:
X_tst=np.array(x_test).reshape(-1,1)
y_pred=lr.predict(X_tst)

In [36]:
y_pred

array([83.89727817, 27.15092273, 27.15092273])

In [40]:
X_tst

array([[8.3],
       [2.5],
       [2.5]])

In [38]:
X_tst_9_25=np.array([9.25]).reshape(-1,1)
y_pred_9_25=lr.predict(X_tst_9_25)

In [39]:
y_pred_9_25

array([93.19193983])

In [41]:
score=lr.score(X_tst, y_test)

In [42]:
score

0.974047128713709

In [46]:
print("Score of a person studying 9.25 hours is: ",y_pred_9_25[0])

Score of a person studying 9.25 hours is:  93.19193983315074
